data:
  train_images_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/train/images"
  train_masks_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/train/masks"

  test_images_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/test/images"
  test_masks_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/test/masks"

  val_images_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/val/images"
  val_masks_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_30/val/masks"

  plot_image_ids_path: "/home/prajter/PycharmProjects/Flair-2/notebooks/test_split/test_plot_ids.npy"

  dataset_version: "split_40"
  num_classes: 13
  batch_size: 8
  num_workers: 12
  selected_channels: [ 0, 1, 2, 3, 4 ]
  seed: 42
  apply_augmentation: true
  augmentation_prob: 0.5
  other_class_index: 12 # we are indexing from 1, so 12 is the 13th class


mlflow:
  name: "aerial_images-only"
  run_name: "DeepLabV3Plus_efficientnet_b5_cross_entropy_split_45"
#  run_name: "TEST"
  tracking_uri: "file:///home/prajter/PycharmProjects/Flair-2/data/results/mlruns"
  notes: "pipeline_test"
  requirements_path: "/home/prajter/PycharmProjects/Flair-2/requirements.txt"

model:
  model_type: "DeepLabV3Plus"
  encoder_name: "efficientnet-b4"
  encoder_weights: "imagenet"
  activation: None

training:
  device: "cuda"
  learning_rate: 1e-4
  weight_decay: 1e-5
  optimizer: "AdamW"
  epochs: 10
  early_stopping_patience: 3
  loss_function:
    type: "SoftCrossEntropyLoss"
    args:
#      mode: "multiclass"
#      from_logits: true
#      reduction: mean
      smooth_factor: 0.0
      ignore_index: 12

optimizer:
  betas: [ 0.9, 0.95 ]
  weight_decay: 0.001

evaluation:
  log_confusion_matrix: true
  log_comparison: true
  eval_per_sample: true
