data:
  train:
    images: "/Users/test/P/flair-2/data/flair_2_toy_aerial_train"
    masks: "/Users/test/P/flair-2/data/flair_2_toy_labels_train"

  val:
    images: "/Users/test/P/flair-2/data/flair_2_toy_aerial_test"
    masks: "/Users/test/P/flair-2/data/flair_2_toy_labels_test"

  test:
    images: "/Users/test/P/flair-2/data/flair_2_toy_aerial_test"
    masks: "/Users/test/P/flair-2/data/flair_2_toy_labels_test"
  
  plot_image_ids_path: ""
  dataset_version: "split_40"
  num_classes: 13
  batch_size: 4
  num_workers: 0
  selected_channels: [0, 1, 2, 3, 4]
  other_class_index: 12

  data_augmentation:
    apply_augmentations: true
    augmentations:
      hflip:
        prob: 0.5
      vflip:
        prob: 0.5
      rotation:
        prob: 0.5
        angles: [0, 90, 180, 270]
      contrast:
        prob: 0.5
        range: [0.8, 1.2]
      brightness:
        prob: 0.5
        range: [0.8, 1.2]

mlflow:
  name: "aerial_images-only"
  run_name: "DeepLabV3Plus_efficientnet_b5_cross_entropy_split_45"
  tracking_uri: null
  note: "pipeline_test"
  dagshub:
    enabled: true
    repo_owner: "prajter00"
    repo_name: "flair-2"
    branch: null

model:
  model_type: "Segformer"
  encoder_name: "mit_b0"
  encoder_weights: "imagenet"
  activation: null

training:
  device: "cuda"
  optimizer:
    type: "AdamW"
    learning_rate: 1e-4
    betas: [0.9, 0.95]
    weight_decay: 1e-5
  epochs: 2
  early_stopping_patience: 3
  loss_function:
    type: "LovaszLoss"
    args:
#      smooth_factor: 0.0
#      ignore_index: 12
      mode: "multiclass"

experiment:
  seed: 42
  deterministic: true

evaluation:
  log_confusion_matrix: true
  log_comparison: true
  log_sample_ids: ["006512",  "006975"]

visualization:
  language: "pl"  # or "en" for English
  labels:
    ground_truth: "Rzeczywistość"
    prediction: "Predykcja"
    predicted_class: "Klasa przewidywana"
    actual_class: "Klasa rzeczywista"
    confusion_matrix_title: "Macierz pomyłek"


