masks_train_dir:  "/home/prajter/PycharmProjects/Flair-2/data/flair_labels_train"
images_train_dir: "/home/prajter/PycharmProjects/Flair-2/data/flair_aerial_train"
masks_test_dir:  "/home/prajter/PycharmProjects/Flair-2/data/flair_2_labels_test"
images_test_dir: "/home/prajter/PycharmProjects/Flair-2/data/flair_2_aerial_test"
output_dir: "/home/prajter/PycharmProjects/Flair-2/data/split_10"
train_sample_percentage: 0.1
val_split: 0.15
test_plot_count: 25
num_classes: 13
random_state: 42